package: retry volume detach
`hdiutil detach` is flaky so this retries to avoid breaking. It also
does `-force` for the last retry.

diff --git a/package/create-dmg/create-dmg b/package/create-dmg/create-dmg
--- a/package/create-dmg/create-dmg
+++ b/package/create-dmg/create-dmg
@@ -12,6 +12,17 @@ function version() {
 	echo "create-dmg $(pure_version)"
 }
 
+function hdiutil-detach-retry() {
+	for i in 1 2 3 4 5; do
+		if [ "$i" -eq "5" ]; then
+			FORCE="-force"
+		else
+			FORCE=""
+		fi
+		hdiutil detach "$1" && break || sleep 1
+	done
+}
+
 function usage() {
 	version
 	echo "Creates a fancy DMG file."
@@ -293,7 +304,7 @@ MOUNT_DIR="/Volumes/${VOLUME_NAME}"
 # try unmount dmg if it was mounted previously (e.g. developer mounted dmg, installed app and forgot to unmount it)
 echo "Unmounting disk image..."
 DEV_NAME=$(hdiutil info | egrep --color=never '^/dev/' | sed 1q | awk '{print $1}')
-test -d "${MOUNT_DIR}" && hdiutil detach "${DEV_NAME}"
+test -d "${MOUNT_DIR}" && hdiutil-detach-retry "${DEV_NAME}"
 
 echo "Mount directory: $MOUNT_DIR"
 DEV_NAME=$(hdiutil attach -readwrite -noverify -noautoopen "${DMG_TEMP_NAME}" | egrep --color=never '^/dev/' | sed 1q | awk '{print $1}')
@@ -358,7 +369,7 @@ if [ $SKIP_JENKINS -eq 0 ]; then
 	applescript_source | sed -e "s/WINX/$WINX/g" -e "s/WINY/$WINY/g" -e "s/WINW/$WINW/g" -e "s/WINH/$WINH/g" -e "s/BACKGROUND_CLAUSE/$BACKGROUND_CLAUSE/g" -e "s/REPOSITION_HIDDEN_FILES_CLAUSE/$REPOSITION_HIDDEN_FILES_CLAUSE/g" -e "s/ICON_SIZE/$ICON_SIZE/g" -e "s/TEXT_SIZE/$TEXT_SIZE/g" | perl -pe  "s/POSITION_CLAUSE/$POSITION_CLAUSE/g" | perl -pe "s/QL_CLAUSE/$QL_CLAUSE/g" | perl -pe "s/APPLICATION_CLAUSE/$APPLICATION_CLAUSE/g" | perl -pe "s/HIDING_CLAUSE/$HIDING_CLAUSE/" >"$APPLESCRIPT"
 	sleep 2 # pause to workaround occasional "Can’t get disk" (-1728) issues
 	echo "Running Applescript: /usr/bin/osascript \"${APPLESCRIPT}\" \"${VOLUME_NAME}\""
-	(/usr/bin/osascript "${APPLESCRIPT}" "${VOLUME_NAME}" || if [[ "$?" -ne 0 ]]; then echo "Failed running AppleScript"; hdiutil detach "${DEV_NAME}"; exit 64; fi)
+	(/usr/bin/osascript "${APPLESCRIPT}" "${VOLUME_NAME}" || if [[ "$?" -ne 0 ]]; then echo "Failed running AppleScript"; hdiutil-detach-retry "${DEV_NAME}"; exit 64; fi)
 	echo "Done running the applescript..."
 	sleep 4
 	rm "$APPLESCRIPT"
@@ -385,7 +396,7 @@ fi
 
 # unmount
 echo "Unmounting disk image..."
-hdiutil detach "${DEV_NAME}"
+hdiutil-detach-retry "${DEV_NAME}"
 
 # compress image
 echo "Compressing disk image..."
